version: "3"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.0
    ports:
      - 8081:8081
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

